---

- name: "Uninstall Netbox entirely"
  become: true
  command: '/opt/bin/docker-compose down'
  args:
    chdir: "{{ docker_netbox__install_dir }}"
  changed_when: False
  failed_when: False

- name: "Uninstall Netbox entirely"
  become: true
  command: 'rm -rf /opt/netbox'
  args:
    chdir: "/opt"
  changed_when: False

- name: "Uninstall Netbox entirely"
  become: true
  command: 'docker volume prune --force'
  args:
    chdir: "/opt"
  changed_when: False