file_sync__container_name: file_sync
file_sync__image: "dexpops/docker-file-sync:latest"
file_sync__restart: no
file_sync__restart_policy: always
file_sync__state: started
file_sync__hostname: "{{ ansible_hostname }}"
file_sync__volumes: []
file_sync__timezone: "{{ timezone__zone }}"
file_sync__method: "wget"
file_sync__wget_url: "http://example.com/filename.tar"
file_sync__wget_dir: "/file_dir"
file_sync__wget_file_name: "filename.tar"
file_sync__wget_fisnihed_marker: ".finished"
# wget http://utxosets.blob.core.windows.net/public/utxo-snapshot-bitcoin-mainnet-551636.tar