---

- name: Main | Load distro-specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- import_tasks: check_vars.yml
  tags:
    - docker_systemd_service
    - docker_systemd_service:check_vars
    - check_vars

- import_tasks: image.yml
  when: docker_systemd_service__state != "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:image
    - image

- import_tasks: install.yml
  when: docker_systemd_service__state != "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:install
    - install

- import_tasks: uninstall.yml
  when: docker_systemd_service__state == "absent"
  tags:
    - docker_systemd_service
    - docker_systemd_service:uninstall
    - uninstall
