---
- name: Uninstall | Remove ENV file for {{ docker_systemd_service__name }}_container.service
  become: true
  file:
    path: "{{ docker_systemd_service__sysconf_dir }}/{{ docker_systemd_service__name }}"
    state: absent

- name: "Uninstall | Disable and stop {{ docker_systemd_service__name }} for state {{ docker_systemd_service__state }}"
  become: true
  ignore_errors: yes
  systemd:
    name: '{{ docker_systemd_service__name }}_container.service'
    enabled: False
    state: stopped

- name: "Uninstall | Disable and stop {{ docker_systemd_service__name }}_container_restart.path for state {{ docker_systemd_service__state }}"
  become: true
  ignore_errors: yes
  systemd:
    name: "{{ docker_systemd_service__name }}_container_restart.path"
    enabled: False
    state: stopped

- name: "Uninstall | Disable and stop {{ docker_systemd_service__name }}_container_restart.service for state {{ docker_systemd_service__state }}"
  become: true
  ignore_errors: yes
  systemd:
    name: "{{ docker_systemd_service__name }}_container_restart.service"
    enabled: False
    state: stopped

- name: Uninstall | Remove unit {{ docker_systemd_service__name }}_container.service'
  become: true
  ignore_errors: yes
  file:
    path: /etc/systemd/system/{{ docker_systemd_service__name }}_container.service
    state: absent

- name: "Uninstall | Remove unit {{ docker_systemd_service__name }}_container_restart.path"
  become: true
  ignore_errors: yes
  file:
    path: "/etc/systemd/system/{{ docker_systemd_service__name }}_container_restart.path"
    state: absent

- name: "Uninstall | Remove unit {{ docker_systemd_service__name }}_container_restart.service"
  become: true
  ignore_errors: yes
  file:
    path: "/etc/systemd/system/{{ docker_systemd_service__name }}_container_restart.service"
    state: absent

- name: Uninstall | Reload systemd units
  become: true
  command: systemctl daemon-reload
  changed_when: False