---

#
# Checking that required variables are set
#
- name: Checking that required variables are set
  fail: msg="{{ item }} is empty or not defined"
  when: vars[item] is undefined or vars[item] == ""
  with_items:
    - docker_vpncloud__container_name
    - docker_vpncloud__image
    - docker_vpncloud__restart
    - docker_vpncloud__restart_policy
    - docker_vpncloud__state
    - docker_vpncloud__hostname
    - docker_vpncloud__volumes
    - docker_vpncloud__port
    - docker_vpncloud__peer_timeout
    - docker_vpncloud__dst_timeout
    - docker_vpncloud__magic
    - docker_vpncloud__shared_key
    - docker_vpncloud__crypto
    - docker_vpncloud__device_name
    - docker_vpncloud__device_type
    - docker_vpncloud__mode
    - docker_vpncloud__subnets
    - docker_vpncloud__ipv4_address
    - docker_vpncloud__mtu
    - docker_vpncloud__ifup
    - docker_vpncloud__ifdown
    - docker_vpncloud__user
    - docker_vpncloud__group