docker_file_sync__container_name: file_sync
docker_file_sync__image: "dexpops/docker-file-sync:latest"
docker_file_sync__restart: no
docker_file_sync__restart_policy: always
docker_file_sync__state: started
docker_file_sync__hostname: "{{ ansible_hostname }}"
docker_file_sync__volumes: []
docker_file_sync__method: "wget"
docker_file_sync__wget_url: "http://example.com/filename.tar"
docker_file_sync__wget_dir: "/file_dir"
docker_file_sync__wget_file_name: "filename.tar"
docker_file_sync__wget_fisnihed_marker: ".finished"
# wget http://utxosets.blob.core.windows.net/public/utxo-snapshot-bitcoin-mainnet-551636.tar