- name: "Container | Handle blocknetdx"
  become: true
  docker_container:
    name: "{{ docker_blocknetdx__container_name}}"
    image: "{{ docker_blocknetdx__image}}"
    restart: "{{ docker_blocknetdx__restart }}"
    restart_policy: "{{ docker_blocknetdx__restart_policy }}"
    state: "{{ docker_blocknetdx__state }}"
    hostname: "{{ docker_blocknetdx__hostname }}"
    volumes: "{{ docker_blocknetdx__volumes }}"
    network_mode: bridge
    ports:
      - "41412:41412"
    env:
      FAST_SYNC_MODE: "{{ docker_blocknetdx__fast_sync_mode | default(omit) }}"