---

#
# Checking that required variables are set
#
- name: Checking that required variables are set
  fail: msg="{{ item }} is empty or not defined"
  when: vars[item] is undefined or vars[item] == ""
  with_items:
    - insn_masternode__container_name
    - insn_masternode__image
    - insn_masternode__restart
    - insn_masternode__restart_policy
    - insn_masternode__state
    - insn_masternode__hostname
    - insn_masternode__volumes
    - insn_masternode__timezone
    - insn_masternode__rpc_password
    - insn_masternode__rpc_port
    - insn_masternode__listen_port