# ------------------------------------------------------------------------------------------
# Maintainer: Karsten Kaj Jakobsen <karsten@karstenjakobsen.dk>
# Deploy and setup infrastructure
# ------------------------------------------------------------------------------------------

- import_playbook: __partial_bootstrap_python.yml
  tags:
    - infrastructure:bootstrap_python

- import_playbook: __partial_docker_consul.yml
  tags:
    - infrastructure:consul