# ------------------------------------------------------------------------------------------
# Maintainer: Karsten Kaj Jakobsen <karsten@karstenjakobsen.dk>
# Deploy and setup bitcoin services
# ------------------------------------------------------------------------------------------

- import_playbook: __partial_netbox.yml

- import_playbook: __partial_bitcoind.yml